# -*- coding: utf-8 -*-
"""Copy of Multiple_PDF_files.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mIO99-4QWgIKvjgAFj0vvEbQi5xgNCPk

### Installation
"""

#!pip install langchain
#!pip install unstructured
#!pip install openai
#!pip install chromadb
#!pip install Cython
#!pip install tiktoken

"""### Load Required Packages"""

from langchain.document_loaders import UnstructuredPDFLoader
from langchain.indexes import VectorstoreIndexCreator

"""### OpenAI API Key"""

# Get your API keys from openai, you will need to create an account. 
# Here is the link to get the keys: https://platform.openai.com/account/billing/overview
import os
#os.environ["OPENAI_API_KEY"] = "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"

"""### Connect Google Drive"""

# connect your Google Drive
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)
root_dir = "/content/gdrive/My Drive/"

pdf_folder_path = f'{root_dir}/data/'
os.listdir(pdf_folder_path)



"""### Load Multiple PDF files"""

# location of the pdf file/files. 
loaders = [UnstructuredPDFLoader(os.path.join(pdf_folder_path, fn)) for fn in os.listdir(pdf_folder_path)]

loaders

"""### Vector Store 
Chroma as vectorstore to index and search embeddings


There are three main steps going on after the documents are loaded:

- Splitting documents into chunks

- Creating embeddings for each document

- Storing documents and embeddings in a vectorstore

"""

#!pip install unstructured[local-inference]

index = VectorstoreIndexCreator().from_loaders(loaders)


#index.query('What was the main topic of the address?')

index.query('List Holidays of India?')

index.query_with_sources('What are the different types of tourism? ')

index.query_with_sources('How many total holidays india have?')



#pdf_folder_path = '/content/gdrive/My Drive/data_2/'
#os.listdir(pdf_folder_path)

# location of the pdf file/files. 
#loaders = [UnstructuredPDFLoader(os.path.join(pdf_folder_path, fn)) for fn in os.listdir(pdf_folder_path)]
#index = VectorstoreIndexCreator().from_loaders(loaders)
#index
