client_config_backend: file
client_config:
    client_id: 398388491549-tu6ls5fi6ara0d92uvu2p4o795cfu7en.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive